-- 카테고리 생성
-- (category_id는 외래 키로 tag_category와 연결되어 있어야 하므로 반드시 먼저 수행)
INSERT IGNORE INTO tag_category (category_name) VALUES ('IT·프로그래밍');
INSERT IGNORE INTO tag_category (category_name) VALUES ('디자인');
INSERT IGNORE INTO tag_category (category_name) VALUES ('마케팅');

-- IT·프로그래밍 태그
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('워드프레스', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('JavaScript', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Java', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Python', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('PHP', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('C#', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Perl', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('TypeScript', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('React', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Angular', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('ASP.NET', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Bootstrap', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Flash', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('JSP', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Vue.js', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('ASP', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Node.js', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('그누보드', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('XE', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('모두', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Wix', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('카페24', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('고도몰', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('메이크샵', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('영카트', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('식스샵', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Swift', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Android Studio', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('C#.NET', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Visual Basic', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Lua', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Objective-C', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Go', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Arduino', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('AVR', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Raspberry Pi', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('STM32', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Erlang', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Verilog', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('VHDL', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Excel', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('R', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Matlab', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('SPSS', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('SAS', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Scala', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Tableau', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Power BI', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('SQL', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Minitab', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Julia', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('jQuery', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Unity', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Google SDK', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Unreal Engine', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Godot', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Construct', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('GameMaker Studio', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Vuforia', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Kudan', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Visual Studio', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('HTML', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('CSS', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Ruby', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Ruby on Rails', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('C', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('C++', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Visual Basic.NET', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Delphi', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Object Pascal', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('A#', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('ActionScript', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Assembly', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Autohotkey', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('AutoIt', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Clojure', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Dart', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Kotlin', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('LabVIEW', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Liquid', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Rust', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Sass', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Solidity', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('XML', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('.NET', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Bulma', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('CodeIgniter', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Django', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Electron', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Express.js', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('FastAPI', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Flask', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Flutter', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Foundation', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Framework7', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Ionic', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Laminas', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Laravel', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Material-UI', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Materialize', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Next.js', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Qt', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('React Native', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Spring', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Swing', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('WPF', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Xamarin', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Angular JS', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Adobe Photoshop', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Adobe XD', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Axure RP', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Balsamiq Mockups', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Figma', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Framer', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Google Presentation', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Illustrator', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Invision', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Oven', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Pixate', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('PowerMockup', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Microsoft Powerpoint', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('protoNow', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('ProtoPie', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Sketch', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('UXPin', 1);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Zeplin', 1);

-- 디자인 태그
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Adobe Photoshop', 2);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Adobe Illustrator', 2);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Adobe Creative Suite', 2);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Adobe Dreamweaver', 2);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Adobe Flash', 2);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Adobe XD', 2);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Indesign', 2);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('MicroSoft PowerPoint', 2);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Paint tool sai', 2);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('sketch up', 2);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Corel Painter', 2);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Sketch3', 2);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Sketchapp', 2);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Zeplin', 2);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('HTML & CSS', 2);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Keyshot', 2);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('3D MAX', 2);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Rhino3D', 2);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('CATIA', 2);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('3D CAD', 2);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('PRO-E', 2);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Fusion360', 2);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('MAYA', 2);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Zbrush', 2);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Cinema4d', 2);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Redshift', 2);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Arnold', 2);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Substance Painter', 2);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('CAD', 2);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('v-ray', 2);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Figma', 2);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('after effect', 2);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('auto cad', 2);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('blender', 2);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('lumion', 2);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Live2D Cubism', 2);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Vtube Studio', 2);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Procreate', 2);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Unity', 2);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Unreal Engine', 2);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Substance painter', 2);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Inventor', 2);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Spark AR', 2);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('QUARKXPRESS', 2);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('인테리어 시공', 2);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('간판 시공', 2);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('ProtoPie', 2);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('SolidWorks', 2);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Enscape', 2);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Adobe Substance 3D', 2);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('Adobe Lightroom', 2);

-- 마케팅 태그
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('인스타그램 관리', 3);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('키워드∙검색 광고', 3);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('블로그 관리', 3);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('카페 관리', 3);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('검색최적화·SEO', 3);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('쇼핑몰 운영 대행', 3);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('해외 언론홍보', 3);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('언론 홍보', 3);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('포털질문·답변', 3);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('블로그 체험단', 3);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('인스타그램 체험단', 3);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('유튜브 체험단', 3);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('유튜브 관리', 3);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('B모임 관리', 3);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('메신저 채널 관리', 3);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('앱 마케팅', 3);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('디스플레이∙영상∙배너', 3);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('SNS 광고', 3);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('버스·지하철·택시 광고', 3);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('전광판·키오스크 광고', 3);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('신문·잡지 광고', 3);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('TV·라디오 광고', 3);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('개인 인플루언서', 3);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('블로그 포스팅', 3);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('카페 바이럴', 3);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('SNS 포스팅', 3);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('종합광고대행', 3);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('쇼핑몰 활성화', 3);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('쇼핑 태그 설치', 3);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('마케팅 패키지', 3);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('CPA 마케팅', 3);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('라이브커머스', 3);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('메시지 마케팅', 3);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('지도 최적화', 3);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('행사·이벤트', 3);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('마케팅 컨설팅', 3);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('데이터 성과 분석', 3);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('해외 검색', 3);
INSERT IGNORE INTO tag_option (tag_name, category_id) VALUES ('해외 SNS', 3);
